import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import Link from 'next/link'

const Home: NextPage = (props: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      <Head>
        <title>PokeFight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
        <>
          <div className="mt-6 grid grid-cols-3 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:gap-x-8">
            {!props.pokemon ? <div>Loading</div> :
              <>
                {props.pokemon.results.map((p: any, i: number) =>
                  <div key={i} className="group relative">
                    <div className="w-full min-h-80 bg-pokemon-blue aspect-w-1 aspect-h-1 rounded-md overflow-hidden group-hover:opacity-75 lg:h-20 lg:aspect-none text-pokemon-yellow text-center">
                        <div className="justify-center items-center">
                          <Link href={`/pokemon/${(i + 1)}`}><span className='capitalize'>{p.name}</span></Link>
                        </div>
                    </div>
                  </div>)}
              </>}
          </div>
        </>
      </main>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const res = fetch('https://pokeapi.co/api/v2/pokemon/?limit=150');

  return {
    props: {
      pokemon: await (await res).json(),
    }
  }
}